#!/usr/bin/env python3
"""Add all remaining screen dictionary entries to en.ts and th.ts."""
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent / "src" / "i18n" / "dictionaries"

# ── English entries ──────────────────────────────────────────────────
EN_BLOCK = """
  chat: {
    yesterday: 'Yesterday',
    daysAgo: '{count} days ago',
    quickReplyInterested: "I'm interested in this job",
    quickReplyDocsSent: "I've sent you the latest documents",
    quickReplyMoreDetails: 'Could I get a bit more detail?',
    quickReplyWhenToChat: 'When would be a good time to chat?',
    hide: 'Hide',
    delete: 'Delete',
    unknownUser: 'User',
    startConversation: 'Start a conversation',
    messagesTitle: 'Messages',
    notLoggedIn: 'Not logged in',
    loginToSeeMessages: 'Log in to see your conversations',
    deleteConversationTitle: 'Delete conversation',
    deleteConversationMessage: 'Remove chat with "{name}" from your list?',
    cancel: 'Cancel',
    error: 'Error',
    deleteConversationError: 'Unable to delete conversation',
    searchPlaceholder: 'Search conversations...',
    firstVisitTipTitle: 'All messages are gathered here',
    firstVisitTipDescription: 'When you contact from a post, a chat room is auto-created. Swipe to hide or delete rooms. You can review usage anytime from the guide.',
    viewGuide: 'View guide',
    noMessages: 'No messages yet',
    noMessagesDescription: 'When you contact a poster, messages will appear here',
    swipeHint: '💡 Swipe left = delete · Swipe right = hide',
    hiddenChatsTitle: 'Hidden chats ({count})',
    noHiddenChats: 'No hidden chats',
    unhide: 'Unhide',
    messageDeleted: '🗑 This message was deleted',
    tapToOpen: 'Tap to open',
    openDocError: 'Unable to open document',
    attachedDocument: 'Attached document',
    tapToOpenDocument: 'Tap to open document',
    openMapError: 'Unable to open map',
    pinnedLocation: 'Pinned location',
    tapToOpenMap: 'Tap to open in map',
    chatClosed: 'This chat has been closed',
    sendMessageFailed: 'Cannot send message',
    sendImageFailed: 'Failed to send image',
    sendDocFailed: 'Cannot send document',
    pleaseTryAgain: 'Please try again',
    sendLocationFailed: 'Cannot send location',
    cannotDelete: 'Cannot delete',
    cannotSaveImage: 'Cannot save image',
    grantPhotoPermission: 'Please grant photo access permission first',
    storageNotFound: 'Storage not found',
    savedSuccessfully: 'Saved successfully',
    imageSavedToAlbum: 'Image saved to NurseGo album',
    inputPlaceholder: 'Type a message, or select a quick reply above',
    quickReplies: 'Quick replies',
    tapToSendInstantly: 'Tap to send instantly',
    manageMessage: 'Manage message',
    deleteMessage: 'Delete this message',
    attachInChat: 'Attach in chat',
    choosePhoto: 'Choose photo from device',
    sendFromMyDocuments: 'Send document from My Documents',
    sendPinnedLocation: 'Send pinned location',
    chooseUploadedDoc: 'Choose uploaded document',
    noSavedDocuments: 'No documents in My Documents yet',
    reset: 'Reset',
    imageViewerHint: 'Pinch to zoom/drag, or use zoom & download buttons above',
  },
  myPosts: {
    title: 'My posts',
    pressBackToExit: 'Press back again to exit',
    error: 'An error occurred',
    loadPostsError: 'Unable to load posts',
    closePostTitle: 'Close post',
    closePostMessage: 'Do you want to close this post?\\nPeople will no longer see it',
    cancel: 'Cancel',
    closePost: 'Close post',
    success: 'Success',
    postClosed: 'Post closed successfully',
    closePostError: 'Unable to close post',
    postReactivated: 'Post reactivated successfully',
    reactivatePostError: 'Unable to reactivate post',
    urgentQuotaUsed: 'Urgent badge quota used up',
    urgentQuotaUsedReason: "This account's monthly urgent badge quota is used up",
    urgentQuotaUsedDetail: 'Monthly urgent badge quota used. You can still post and manage normally.',
    markedUrgent: 'Post marked as urgent',
    premiumPerkTitle: '🎁 Premium perk',
    premiumPerkMessage: 'This account has 1 free Premium urgent badge.\\nHelps your post get seen faster.\\n\\nUse it now?',
    useFreePerk: '🎁 Use free perk',
    updateError: 'Unable to update',
    markUrgentTitle: '⚡ Mark as urgent',
    markUrgentMessage: 'Helps post "{title}" get seen faster when payments launch',
    acknowledged: 'Acknowledged',
    freeTrialMode: 'Still in free trial',
    freeTrialUrgentNote: "The system is still free, so there's no actual payment for urgent badges yet",
    deletePostTitle: '🗑️ Delete post',
    deletePostMessage: 'Delete this post permanently?\\nThis action cannot be undone',
    deletePermanently: 'Delete permanently',
    postDeleted: 'Post deleted successfully',
    deletePostError: 'Unable to delete post',
    extendPostTitle: '⏰ Extend post',
    extendPostMessage: 'Extend post "{title}" by 1 day',
    extendNow: 'Extend now',
    pleaseLogin: 'Please log in',
    accountNotFound: 'Account info not found for using this perk',
    extendQuotaUsed: 'Extend quota used up',
    extendQuotaUsedReason: 'Monthly post extension quota used up',
    postExtended: 'Post extended by 1 day',
    freeTrialExtendNote: 'System is still free, no real payment for post extension yet',
    extendPostError: 'Unable to extend post',
    startDateAsAgreed: 'Start date as agreed',
    workHoursAsAgreed: 'Work hours as agreed',
    salary: 'Salary',
    compensation: 'Compensation',
    statusActive: 'Active',
    statusUrgent: 'Urgent',
    statusClosed: 'Closed',
    statusExpired: 'Expired',
    statusDeleted: 'Deleted',
    notSpecified: 'Not specified',
    baht: 'baht',
    perHour: '/hr',
    perDay: '/day',
    perMonth: '/month',
    perShift: '/shift',
    posted: 'Posted ',
    expired: 'Expired',
    daysLeft: '{count} days left',
    tapToManage: 'Tap to manage',
    filterAll: 'All',
    loginToViewPosts: 'Log in to view your posts',
    login: 'Log in',
    noPosts: 'No posts yet',
    noPostsDescription: "You haven't created any posts. Try creating one!",
    createPost: 'Create post',
    noPostsInFilter: 'No posts in this category',
    viewApplicants: 'View applicants',
    edit: 'Edit',
    extendPost: 'Extend post',
    markUrgent: 'Mark as urgent',
    reactivate: 'Reactivate',
  },
  notifications: {
    title: 'Notifications',
    today: 'Today',
    yesterday: 'Yesterday',
    thisWeek: 'This week',
    error: 'An error occurred',
    markAllReadError: 'Unable to mark all as read',
    deleteNotificationTitle: 'Delete notification',
    deleteNotificationMessage: 'Do you want to delete this notification?',
    cancel: 'Cancel',
    delete: 'Delete',
    deleteError: 'Unable to delete',
    unknownUser: 'User',
    loginToView: 'Log in to view notifications',
    loginSubtitle: 'Receive new job and message notifications',
    login: 'Log in',
    loading: 'Loading...',
    markAllRead: 'Read all',
    empty: 'No notifications',
    emptySubtitle: 'New activity will appear here',
  },
  payment: {
    transitionReviewTitle: 'Payment activation review period reached',
    monthlyQuotaTitle: 'Monthly quota usage period',
    livePaymentTitle: 'Live payment system active',
    transitionReviewDesc: 'System reached review threshold but remains free until admin approves live billing',
    monthlyQuotaDesc: "App doesn't charge real money yet. Features are managed via monthly account quotas",
    livePaymentDesc: 'This status is used when admin approves billing and payment gateway is ready',
    gatewayReadyAwaitingApproval: 'Payment gateway ready but awaiting admin approval',
    awaitingGateway: 'Awaiting payment gateway before review can proceed',
    quotaManagedNote: 'Core features and add-ons managed via monthly account quotas',
    noChargesNote: 'No payment simulation and no charges at this stage',
    livePaymentReady: 'Payment system ready and active in this state',
    paymentNotReady: 'Payment system not ready, cannot enable billing yet',
    willNotifyBeforeLaunch: "When payments launch, we'll notify you with details first",
    currentStatus: 'Current status',
    activeAmount: 'Active amount',
    noCharges: 'No charges yet',
    baht: 'baht',
    continueUsing: 'Continue using app',
    closePage: 'Close this page',
  },
  favorites: {
    title: '❤️ Favorites',
    noResults: 'No results found',
    noSavedJobs: 'No saved jobs yet',
    tryDifferentSearch: 'Try a different search',
    tapToSave: 'Tap ❤️ to save jobs you\\'re interested in',
    perHour: '/hr',
    perDay: '/day',
    perMonth: '/month',
    perShift: '/shift',
    negotiable: 'Negotiable',
    postExpired: 'Post expired',
    urgent: '⚡ Urgent',
    noFacility: 'No facility specified',
    removeTitle: 'Remove from favorites',
    removeMessage: 'Remove "{title}" from favorites?',
    cancel: 'Cancel',
    remove: 'Remove',
    searchPlaceholder: 'Search job title, hospital, location...',
    loading: 'Loading...',
    resultCount: 'Found {filtered} of {total} items',
  },
  map: {
    locationNotFoundTitle: 'Location not found',
    locationNotFoundMessage: 'Please enable GPS and try again',
    seeRate: 'See rate',
    rateUnitShift: '/shift',
    rateUnitHour: '/hr',
    rateUnitDay: '/day',
    rateUnitMonth: '/month',
    loading: 'Loading...',
    jobsOnMap: '{count} jobs on map',
    searchPlaceholder: 'Search job name or location',
    searchChipLabel: 'Search: {term}',
    sortRateDesc: 'Sort: Highest pay',
    sortNearby: 'Sort: Near me',
    urgentOnly: 'Urgent only',
    legendUrgent: 'Urgent',
    loadingJobs: 'Loading jobs...',
    jobFallbackTitle: 'Job',
    urgentTag: '⚡ Urgent',
    viewJob: 'View job',
    filterTitle: 'Filter jobs',
    filterReset: 'Reset',
    filterPostType: 'Post type',
    filterAll: 'All',
    filterProvince: 'Province',
    filterStaffType: 'Staff type',
    filterMinRate: 'Minimum rate',
    filterSortBy: 'Sort by',
    sortLatest: 'Latest',
    sortHighestPay: 'Highest pay',
    sortNearMe: 'Near me',
    filterStatus: 'Status',
    filterUrgentOnly: '⚡ Urgent only',
    filterApply: 'Show {count} results',
    postTypeShift: 'Shift Replacement',
    postTypeJob: 'Job Recruitment',
    postTypeHomecare: 'Patient Care',
  },
  help: {
    headerTitle: 'Help',
    searchPlaceholder: 'Search questions...',
    allCategories: 'All',
    faqSectionTitle: 'Frequently Asked Questions',
    emptySearch: 'No questions match your search',
    contactTitle: 'Contact Us',
    contactSubtitle: "Can't find an answer? Contact our support team",
    contactEmail: 'Email',
    contactPhone: 'Phone',
    officeHours: 'Office hours: Mon–Fri 9:00–18:00',
    emailSubject: 'Request for help',
    onboardingGuideLink: 'View getting started guide',
    termsLink: 'Terms of Service',
    privacyLink: 'Privacy Policy',
    aboutLink: 'About Us',
    quickLinksTitle: 'Related Links',
    catGeneral: 'General',
    catAccount: 'Account',
    catJobs: 'Jobs',
    catApplications: 'Applications',
    catHospital: 'Hospital',
    catPayment: 'Payment',
    faq1Q: 'What is NurseGo?',
    faq1A: 'NurseGo is a job-finding platform for nurses and medical staff. It helps connect job seekers with hospitals, clinics, and agencies quickly and conveniently.',
    faq2Q: 'Is this app free?',
    faq2A: 'Currently the app is in free trial. When billing launches, we will notify all users before any charges apply.',
    faq3Q: 'What devices are supported?',
    faq3A: 'NurseGo supports both iOS and Android smartphones and tablets.',
    faq4Q: 'How do I register?',
    faq4A: 'Tap "Register" on the login screen and follow the steps—enter your phone or email, verify, choose your role, and set up your profile.',
    faq5Q: 'I forgot my password',
    faq5A: 'Tap "Forgot password" on the login screen and enter your registered email. We will send a reset link.',
    faq6Q: 'How do I edit my profile?',
    faq6A: 'Go to the Profile tab, tap the edit icon, and update your information.',
    faq7Q: 'How do I delete my account?',
    faq7A: 'Go to Settings > scroll down > "Delete account". All your data will be permanently removed.',
    faq8Q: 'How do I find the right job?',
    faq8A: 'Use the search bar and filters on the Home tab. You can filter by location, staff type, pay rate, and more.',
    faq9Q: 'How do I save a job?',
    faq9A: 'Tap the ❤️ icon on any job card to save it to your Favorites.',
    faq10Q: 'Where do posted jobs come from?',
    faq10A: 'Jobs are posted by registered hospitals, clinics, agencies, and individuals looking for medical staff.',
    faq11Q: 'How do I apply for a job?',
    faq11A: 'Open the job you are interested in and tap "Interested" or "Quick Apply" at the bottom.',
    faq12Q: 'Where can I check my application status?',
    faq12A: 'Go to the Messages tab to see conversations with posters, or check your recent applications in the Notifications tab.',
    faq13Q: 'Can I cancel an application?',
    faq13A: 'Currently, you cannot cancel once interest is shown. You can notify the poster via chat if your plans change.',
    faq14Q: 'What documents should I upload?',
    faq14A: 'Upload your professional license, national ID, and any relevant certificates to increase your credibility.',
    faq15Q: 'How can a hospital post a job?',
    faq15A: 'Choose the "Hospital / Clinic / Agency" role, complete your profile, and tap the "+" button on the Post tab.',
    faq16Q: 'Where can I view applicants?',
    faq16A: 'Open your post from "My Posts" and tap "View applicants" to see everyone who expressed interest.',
    faq17Q: 'How do hospital reviews help?',
    faq17A: 'Reviews help nurses evaluate workplaces and help hospitals build trust with potential applicants.',
    faq18Q: 'What fees do hospitals pay?',
    faq18A: 'Currently the app is free for all users during launch. When billing launches, pricing details will be announced in advance.',
    faq19Q: 'What payment channels are available?',
    faq19A: 'Payment channels will be announced when the billing system is ready.',
    faq20Q: 'How do I request a receipt?',
    faq20A: 'Receipt issuance will be available when billing goes live. Contact support for any inquiries.',
  },
  reviews: {
    userFallback: 'User',
    workplaceFallback: 'Workplace',
    alertNotice: 'Notice',
    alreadyReviewedJob: 'You already reviewed this job',
    alreadyReviewedPlace: 'You already reviewed this workplace',
    cannotReviewTitle: "Can't review yet",
    cannotReviewMessage: 'You can review after a verified and completed job',
    validationTitle: 'Please fill in',
    validationTitleRequired: 'Please enter review title',
    validationContentRequired: 'Please enter review content',
    successTitle: 'Success',
    successMessage: 'Thank you for your review',
    errorTitle: 'Error occurred',
    errorSubmitFallback: 'Unable to submit review',
    loginTitle: 'Please log in',
    loginHelpfulMessage: 'Log in before marking a review helpful',
    alreadyHelpfulTitle: 'Already marked',
    alreadyHelpfulMessage: 'You already marked this review helpful',
    helpfulErrorTitle: "Can't mark",
    helpfulErrorFallback: 'Unable to save helpfulness score',
    noUserData: 'User information not found',
    noWorkplaceData: 'Workplace information not found',
    goBack: 'Back',
    loading: 'Loading reviews...',
    verified: 'Verified',
    recommend: 'Recommend',
    notRecommend: 'Not recommend',
    helpfulDone: 'Already helpful',
    helpful: 'Helpful',
    report: 'Report review',
    responseFromUser: 'Response from user',
    responseFromWorkplace: 'Response from workplace',
    headerSubtitle: 'Reviews',
    ratingCount: 'reviews',
    writeReview: 'Write Review',
    reviewHint: 'You can review after a verified & completed job with this profile',
    sortLatest: 'Latest',
    sortHighest: 'Highest score',
    sortLowest: 'Lowest score',
    sortMostHelpful: 'Most helpful',
    sortLeastHelpful: 'Least helpful',
    emptyTitle: 'No reviews yet',
    emptySubtitleUser: 'Be the first to review this user',
    emptySubtitlePlace: 'Be the first to review this workplace',
    submitting: 'Submitting...',
    submit: 'Submit',
    rateLabel: 'Rate',
    titleLabel: 'Title *',
    titlePlaceholder: 'e.g. Great work experience',
    detailsLabel: 'Details *',
    detailsPlaceholder: 'Share your experience...',
    prosLabel: 'Pros',
    prosPlaceholder: 'What you liked...',
    consLabel: 'Cons',
    consPlaceholder: 'Things to improve...',
    recommendQuestion: 'Would you recommend to others?',
  },
  verification: {
    error: 'Error',
    firstNameRequired: 'Please enter first name',
    lastNameRequired: 'Please enter last name',
    licenseNumberRequired: 'Please enter license number',
    licenseInvalidFormat: 'Invalid license number format',
    licenseDocRequired: 'Please upload professional license',
    employeeCardRequired: 'Please upload employee card',
    idCardRequired: 'Please upload ID card',
    declarationRequired: 'Please upload signed NurseGo declaration',
    incompleteTitle: 'Incomplete information',
    noNameFallback: 'No name specified',
    submitSuccessTitle: 'Request submitted',
    submitSuccessMessage: 'Your verification request has been submitted. Team will review within 1–3 business days',
    submitErrorFallback: 'Unable to submit verification request',
    tapToUpload: 'Tap to upload',
    loading: 'Loading...',
    verificationType: 'Verification type',
    licenseType: 'License type',
    documentNumber: 'Document number',
    pendingTitle: 'Pending review',
    pendingMessage: 'Your request is under review. Team will review within 1–3 business days',
    applicantName: 'Applicant name',
    tagsFromSurvey: 'Tags from role / survey',
    applicantInfoTitle: 'Applicant information',
    firstName: 'First name',
    firstNamePlaceholder: 'Enter first name',
    lastName: 'Last name',
    lastNamePlaceholder: 'Enter last name',
    licenseInfoTitle: 'License information',
    licenseNumber: 'License number',
    licenseNumberPlaceholder: 'e.g. ว.12345',
    selectType: 'Select type',
    licenseExpiry: 'License expiry date',
    documentsTitle: 'Supporting documents',
    licenseDocLabel: 'Professional license',
    licenseDocDesc: 'Upload license photo for verification',
    employeeCardLabel: 'Employee card / Affiliation document',
    employeeCardDesc: 'Confirm you represent this organization',
    idCardLabel: 'National ID',
    idCardDesc: 'Upload only clear identity data',
    declarationLabel: 'Signed NurseGo declaration',
    declarationDesc: 'Please upload a signed document confirming use with NurseGo',
    privacyNote: 'All documents are used only for identity verification and poster credibility',
    submitting: 'Submitting...',
    submitButton: 'Submit verification',
    selectLicenseTypeTitle: 'Select license type',
    selectImageTitle: 'Select document image',
    pickFromGallery: 'Choose from gallery',
    takePhoto: 'Take photo',
  },
  documents: {
    headerTitle: 'My Documents',
    errorSelectDoc: 'Unable to select document',
    permissionTitle: 'Permission needed',
    permissionMessage: 'Please allow photo access',
    errorSelectImage: 'Unable to select image',
    fileTooLargeTitle: 'File too large',
    fileTooLargeMessage: 'Maximum file size 10MB',
    uploadSuccessTitle: 'Success',
    uploadSuccessMessage: 'Document uploaded successfully',
    uploadErrorMessage: 'Upload failed, please try again',
    cancelRequest: 'Cancel request',
    deleteDocument: 'Delete document',
    confirmCancelRequest: 'Cancel request for "{name}"?',
    confirmDelete: 'Delete "{name}"?',
    cancel: 'Cancel',
    confirm: 'Confirm',
    delete: 'Delete',
    deleteError: 'Unable to delete',
    statusApproved: 'Approved',
    statusRejected: 'Failed verification',
    statusPending: 'Pending review',
    loginTitle: 'Log in to manage documents',
    loginSubtitle: 'Upload resume, licenses and other documents',
    loginButton: 'Log in',
    loading: 'Loading...',
    uploading: 'Uploading...',
    addDocument: 'Add document',
    emptyTitle: 'No documents yet',
    emptySubtitle: 'Add documents to improve job application chances',
    selectTypeTitle: 'Select document type',
    viewDocumentFallback: 'View document',
    statusLabel: 'Status:',
    rejectionReasonLabel: 'Reason for rejection:',
    rejectionInline: 'Reason:',
    error: 'Error',
  },
  feedback: {
    headerTitle: 'Feedback & Reviews',
    loginTitle: 'Please log in',
    loginMessage: 'You must log in before sending feedback',
    validationTitle: 'Please fill in',
    titleRequired: 'Please enter a title',
    messageRequired: 'Please enter a message',
    userFallback: 'User',
    successTitle: 'Feedback sent',
    successMessage: 'Thank you, we will use it to improve the app',
    errorTitle: 'Error',
    rating1: 'Very bad 😢',
    rating2: 'Bad 😕',
    rating3: 'Average 😐',
    rating4: 'Good 😊',
    rating5: 'Excellent 🤩',
    historyTitle: 'Your Feedback History',
    emptyHistory: 'No feedback yet',
    adminResponseLabel: '📢 Reply from team:',
    limitText: 'You already sent feedback today\\nPlease wait until tomorrow',
    rateTitle: 'Rate our app',
    typeTitle: 'Feedback Type',
    messageTitle: 'Your message',
    titlePlaceholder: 'Title',
    messagePlaceholder: 'Details... (Tell us what you like or what to improve)',
    submitButton: '📤 Send Feedback',
    disclaimer: 'Your feedback helps us improve. Team reads every message 💙',
  },
  privacy: {
    headerTitle: 'Privacy Policy',
    emailSubject: 'Questions about personal data',
    lastUpdated: 'Last updated:',
    introTitle: 'Your privacy matters to us',
    introText: 'NurseGo is committed to protecting your personal data. This policy explains what data we collect, how we use it, and your rights regarding your information.',
    summaryTitle: 'Quick Summary',
    summary1: 'We collect only data necessary for the service',
    summary2: 'Your data is encrypted and protected',
    summary3: "We don't sell your data to third parties",
    summary4: 'You can delete your account and data anytime',
    contactTitle: 'Have questions about privacy?',
    contactSubtitle: 'Contact us to inquire or exercise your data rights',
    footerCopyright: '© 2026 NurseGo. All rights reserved.',
    footerNote: 'If new websites or services launch in the future, relevant policies may be updated. We will notify users through appropriate channels.',
  },
  terms: {
    headerTitle: 'Terms of Service',
    lastUpdated: 'Last updated:',
    introText: 'Please read these terms of service carefully. By using NurseGo, you agree to these terms.',
    footerCopyright: '© 2026 NurseGo. All rights reserved.',
  },
  shop: {
    trialTitle: 'Still in free trial phase',
    trialMessage: '{subject} will be available when billing is ready. No charges now.',
    launchAccessTitle: 'Currently still launch phase access',
    launchAccessMessage: "Package {name} isn't charging yet. You can use features within your monthly quota.",
    loginWarning: 'Please log in',
    addonLaunchMessage: "This add-on isn't charging yet. Features managed via monthly quota.",
    addonExtraPost: 'Extra post',
    addonExtendPost: 'Extend post',
    addonUrgent: 'Urgent button',
    codeCopiedTitle: '📋 Copied!',
    codeCopiedMessage: 'Code {code} has been copied',
    clearCodeSuccessTitle: 'Pending code cleared',
    clearCodeSuccessMessage: 'You can enter a new code on the profile page',
    clearCodeErrorTitle: 'Failed to clear code',
    clearCodeErrorMessage: 'Please try again',
    errorTitle: '❌ Error occurred',
    headerTitleFree: 'Account access & services',
    headerTitlePaid: 'Access & packages',
    freeAccessTitle: 'Additional access enabled in this account',
    freeAccessDesc: 'This account can use core features and add-ons during the launch phase, managed via monthly quotas.',
    freeAccessHint: 'Details shown may differ by account type and plan.',
    currentPlanLabel: 'Current package',
    pendingCodeTitle: 'Pending code',
    clearButton: 'Clear',
    discountSummary: 'From ฿{from} to ฿{to}',
    pendingCodeHint: 'System will auto-apply this code on matching purchases',
    sectionAccessTitle: 'Access enabled in this account',
    monthly: 'Monthly',
    annual: 'Annual',
    savingsHint: 'Save ~17%',
    nursePlansTitle: 'Packages for nurses',
    hospitalPlansTitle: 'Packages for hospitals',
    addonsTitle: 'Add-ons available in this account',
    addonsTitlePaid: 'Pay per use',
    extraPostTitle: '1 extra post',
    extraPostDesc: 'Use for flexibility when monthly post quota is near limit',
    seeQuota: 'See account quota',
    extendPostTitle: 'Extend post +1 day',
    extendPostDesc: 'Extend post visibility within add-on quota',
    urgentTitle: 'Urgent button (Urgent)',
    urgentDesc: 'Helps important posts get noticed faster',
    referralTitle: 'Refer a friend',
    referralHeadline: 'Refer a friend → get Pro free for 1 month!',
    referralDesc: 'When friend signs up & upgrades, both get 1 month premium free.',
    referralCodeLabel: 'Your code',
    copyButton: 'Copy',
    statReferred: 'Friends referred',
    statFreeMonths: 'Free months earned',
    statMonthsLeft: 'Months remaining',
    savingsPercent: 'Save {savings}%',
    currentTag: 'Currently active',
    upgradeButton: 'Upgrade',
    includedInAccount: "Included in this account's access",
    perYear: '/year',
    perMonth: '/month',
    selectPlan: 'Select this plan',
    audienceFree: 'Suitable for beginners who don\\'t post often',
    audiencePremium: 'Worth it for general users wanting more access',
    audienceNursePro: 'Worth it for nurses posting shifts weekly',
    audienceHospitalStarter: 'Worth it for organizations posting in cycles',
    audienceHospitalPro: 'Worth it for orgs with multiple ongoing positions',
    audienceHospitalEnterprise: 'Worth it for orgs pushing multiple posts all month',
    hospitalFeature1: 'Post & track applicants within monthly quota',
    hospitalFeature2: 'Manage posts with close, extend, and urgent tools',
    hospitalFeature3: 'Chat with interested candidates directly',
    consumerFeature1: 'Use core features within monthly quota',
    consumerFeature2: 'Save favorite jobs and get notifications',
    consumerFeature3: 'Chat with posters and manage documents',
  },
  chooseRole: {
    title: 'Who are you?',
    subtitle: 'Choose a role for an experience that fits you',
    stepLabel: 'Step 2 / 3',
    nurseTitle: 'Nurse / Medical staff',
    nurseSubtitle: 'Looking for shift work, part-time',
    nurseBullet1: 'Search shifts / part-time jobs',
    nurseBullet2: 'Auto notify nearby jobs',
    nurseBullet3: 'Display professional license',
    hospitalTitle: 'Hospital / Clinic / Agency',
    hospitalSubtitle: 'Want to post for staff',
    hospitalBullet1: 'Post jobs for nurses / CG',
    hospitalBullet2: 'Manage applicants',
    hospitalBullet3: 'View stats + applicant history',
    userTitle: 'General public / Patient relatives',
    userSubtitle: 'Looking for home patient caregiver',
    userBullet1: 'Find caregiver / patient sitter',
    userBullet2: 'View reviews + verify identity',
    userBullet3: 'Chat directly with caregivers',
    staffRN: 'RN — Registered Nurse',
    staffPN: 'PN — Practical Nurse',
    staffNA: 'NA — Nurse Aide',
    staffANES: 'ANES — Nurse Anesthetist',
    staffCG: 'CG — Caregiver',
    staffSitter: 'Patient Sitter',
    staffOther: 'Other',
    orgPublic: 'Public hospital',
    orgPrivate: 'Private hospital',
    orgClinic: 'Clinic',
    orgAgency: 'Recruitment agency',
    userNotFound: 'Logged-in user not found',
    errorTitle: 'Error',
    errorSave: 'Unable to save, please try again',
    staffTypeLabel: 'What type of personnel are you?',
    optional: '(optional)',
    orgTypeLabel: 'Your organization type?',
    saving: 'Saving...',
    continue: 'Continue',
    skip: 'Skip for now',
  },
  onboarding: {
    workFulltime: 'Full-time',
    workParttime: 'Part-time / Temporary',
    workWeekend: 'Weekends only',
    workFlexible: 'Flexible / Any type',
    careElderly: 'General elderly care',
    careBedridden: 'Bedridden patient care',
    carePostSurg: 'Post-surgery / Recovery care',
    careChild: 'Child / Sick child care',
    careTerminal: 'Terminal patient care',
    careOther: 'Other',
    urgencyNow: 'Very urgent',
    urgencyWeek: 'Within 1 week',
    urgencyMonth: 'Within 1 month',
    urgencyPlan: 'Planning ahead',
    step1Title: 'Get started smoothly in minutes',
    step1Subtitle: 'Summary of what your role can do and how to use key features',
    step2Title: 'Where are the main features',
    step2Subtitle: 'View app shortcuts before you start using the app',
    step3Title: 'Customize the app for you',
    step3Subtitle: 'Select basic info so the system recommends accurately',
    badgeNurse: 'For nurses',
    heroNurse: 'Find jobs fast, chat easily, and manage profile in one place',
    heroNurseSubtitle: 'NurseGo sorts jobs matching your skills and preferred area',
    nurseHighlight1: 'Find shift replacements fast',
    nurseHighlight2: 'Chat with posters continuously',
    nurseHighlight3: 'Build profile confidence',
    nurseFeature1: 'Home',
    nurseFeature2: 'Post',
    nurseFeature3: 'Messages',
    nurseFeature4: 'Profile',
    nurseSetupTitle: 'Tell us your work style',
    nurseSetupSubtitle: 'This info helps the app filter jobs accurately from the start',
    badgeHospital: 'For organizations',
    heroHospital: 'Post jobs, view interested candidates, chat in one place',
    heroHospitalSubtitle: 'Org role focuses on systematic posting and applicant management',
    hospitalHighlight1: 'Post jobs quickly',
    hospitalHighlight2: 'View applicants neatly',
    hospitalHighlight3: 'Chat instantly',
    hospitalFeature1: 'Home',
    hospitalFeature2: 'Post',
    hospitalFeature3: 'Messages',
    hospitalFeature4: 'Profile',
    hospitalSetupTitle: 'Basic organization setup',
    hospitalSetupSubtitle: 'Specify province & urgency for better recommendations',
    badgeUser: 'For general users',
    heroUser: 'Find the right caregiver, contact privately, decide confidently',
    heroUserSubtitle: 'App helps you find caregivers matching job type & area',
    userHighlight1: 'View matching posts',
    userHighlight2: 'Check profiles before deciding',
    userHighlight3: 'Contact via convenient channel',
    userFeature1: 'Home',
    userFeature2: 'Post',
    userFeature3: 'Messages',
    userFeature4: 'Profile',
    userSetupTitle: 'Tell us the care type you\\'re interested in',
    userSetupSubtitle: 'We will show matching caregivers based on your preferences',
    noticeText: 'All steps are skippable, revisit from Settings',
    quickActionsTitle: 'Start with these 3 for instant mastery',
    nurseQuick1: '1. Open nearby jobs for fast shift alerts in your area',
    nurseQuick2: '2. Verify identity so employers can decide faster',
    nurseQuick3: '3. Complete profile & reviews for more opportunities',
    hospitalQuick1: '1. Fill org info in profile',
    hospitalQuick2: '2. Create first post from Post tab',
    hospitalQuick3: '3. Track applicants & chat',
    userQuick1: '1. Search caregivers from home first',
    userQuick2: '2. Check profile & reviews before contacting',
    userQuick3: '3. Save posts to compare',
    staffTypeTitle: 'Your professional type',
    staffTypeSubtitle: 'Select multiple if you work in more than one field',
    provinceTitle: 'Frequently used province',
    provinceSubtitle: 'Used to initialize search for better area results',
    provinceSearchPlaceholder: 'Search province...',
    setupSubtext: 'Select only relevant options for better recommendations',
    nurseSetupLabel: 'Work style you\\'re interested in',
    hospitalSetupLabel: 'Urgency in finding staff',
    userSetupLabel: 'Type of care needed',
    summaryTypes: '{count} professional types',
    summaryOptions: '{count} selected options',
    skipAll: 'Skip all',
    goBack: 'Go back',
    skipStep: 'Skip this step',
    next: 'Next',
    enterApp: 'Enter app now',
  },"""

# ── Thai entries ──────────────────────────────────────────────────
TH_BLOCK = """
  chat: {
    yesterday: 'เมื่อวาน',
    daysAgo: '{count} วันที่แล้ว',
    quickReplyInterested: 'สนใจงานนี้ครับ/ค่ะ',
    quickReplyDocsSent: 'ส่งเอกสารล่าสุดให้แล้วครับ/ค่ะ',
    quickReplyMoreDetails: 'ขอรายละเอียดเพิ่มอีกนิดได้ไหมครับ/คะ',
    quickReplyWhenToChat: 'สะดวกคุยต่อช่วงไหนครับ/คะ',
    hide: 'ซ่อน',
    delete: 'ลบ',
    unknownUser: 'ผู้ใช้',
    startConversation: 'เริ่มต้นการสนทนา',
    messagesTitle: 'ข้อความ',
    notLoggedIn: 'ยังไม่ได้เข้าสู่ระบบ',
    loginToSeeMessages: 'เข้าสู่ระบบเพื่อดูข้อความสนทนาของคุณ',
    deleteConversationTitle: 'ลบการสนทนา',
    deleteConversationMessage: 'ลบแชทกับ "{name}" ออกจากรายการของคุณ?',
    cancel: 'ยกเลิก',
    error: 'ผิดพลาด',
    deleteConversationError: 'ไม่สามารถลบการสนทนาได้',
    searchPlaceholder: 'ค้นหาการสนทนา...',
    firstVisitTipTitle: 'ข้อความทั้งหมดจะถูกรวมไว้ที่นี่',
    firstVisitTipDescription: 'เมื่อคุณติดต่อจากหน้าโพสต์ ระบบจะสร้างห้องแชทให้อัตโนมัติ คุณปัดเพื่อซ่อนหรือลบห้องได้ และกลับมาดูภาพรวมการใช้งานจากคู่มือได้ทุกเมื่อ',
    viewGuide: 'ดูคู่มือ',
    noMessages: 'ยังไม่มีข้อความ',
    noMessagesDescription: 'เมื่อคุณติดต่อกับผู้โพสต์ ข้อความจะแสดงที่นี่',
    swipeHint: '💡 ปัดซ้าย = ลบ · ปัดขวา = ซ่อน',
    hiddenChatsTitle: 'แชทที่ซ่อน ({count})',
    noHiddenChats: 'ไม่มีแชทที่ซ่อน',
    unhide: 'นำกลับ',
    messageDeleted: '🗑 ข้อความนี้ถูกลบแล้ว',
    tapToOpen: 'แตะเพื่อเปิด',
    openDocError: 'ไม่สามารถเปิดเอกสารได้',
    attachedDocument: 'เอกสารแนบ',
    tapToOpenDocument: 'แตะเพื่อเปิดเอกสาร',
    openMapError: 'ไม่สามารถเปิดแผนที่ได้',
    pinnedLocation: 'ตำแหน่งที่ปักหมุด',
    tapToOpenMap: 'แตะเพื่อเปิดในแผนที่',
    chatClosed: 'แชทนี้ถูกปิดแล้ว',
    sendMessageFailed: 'ส่งข้อความไม่ได้',
    sendImageFailed: 'ส่งรูปภาพไม่สำเร็จ',
    sendDocFailed: 'ส่งเอกสารไม่ได้',
    pleaseTryAgain: 'กรุณาลองใหม่อีกครั้ง',
    sendLocationFailed: 'ส่งตำแหน่งไม่ได้',
    cannotDelete: 'ไม่สามารถลบได้',
    cannotSaveImage: 'บันทึกรูปไม่ได้',
    grantPhotoPermission: 'กรุณาอนุญาตสิทธิ์เข้าถึงรูปภาพก่อน',
    storageNotFound: 'ไม่พบพื้นที่จัดเก็บไฟล์',
    savedSuccessfully: 'บันทึกสำเร็จ',
    imageSavedToAlbum: 'รูปถูกบันทึกไว้ในอัลบั้ม NurseGo แล้ว',
    inputPlaceholder: 'พิมพ์ข้อความ หรือเลือกข้อความลัดด้านบน',
    quickReplies: 'ข้อความลัด',
    tapToSendInstantly: 'แตะเพื่อส่งทันที',
    manageMessage: 'จัดการข้อความ',
    deleteMessage: 'ลบข้อความนี้',
    attachInChat: 'แนบข้อมูลในแชท',
    choosePhoto: 'เลือกรูปจากเครื่อง',
    sendFromMyDocuments: 'ส่งเอกสารจากเอกสารของฉัน',
    sendPinnedLocation: 'ส่งตำแหน่งแบบปักหมุด',
    chooseUploadedDoc: 'เลือกเอกสารที่อัปไว้แล้ว',
    noSavedDocuments: 'ยังไม่มีเอกสารในหน้าของฉัน',
    reset: 'รีเซ็ต',
    imageViewerHint: 'ใช้ 2 นิ้วซูม/ลาก หรือกดปุ่มซูมและดาวน์โหลดด้านบน',
  },
  myPosts: {
    title: 'ประกาศของฉัน',
    pressBackToExit: 'กดกลับอีกครั้งเพื่อออกจากแอพ',
    error: 'เกิดข้อผิดพลาด',
    loadPostsError: 'ไม่สามารถโหลดประกาศได้',
    closePostTitle: 'ปิดประกาศ',
    closePostMessage: 'คุณต้องการปิดประกาศนี้หรือไม่?\\nผู้คนจะไม่เห็นประกาศนี้อีก',
    cancel: 'ยกเลิก',
    closePost: 'ปิดประกาศ',
    success: 'สำเร็จ',
    postClosed: 'ประกาศถูกปิดเรียบร้อยแล้ว',
    closePostError: 'ไม่สามารถปิดประกาศได้',
    postReactivated: 'เปิดประกาศใหม่เรียบร้อยแล้ว',
    reactivatePostError: 'ไม่สามารถเปิดประกาศได้',
    urgentQuotaUsed: 'ใช้สิทธิ์ป้ายด่วนครบแล้ว',
    urgentQuotaUsedReason: 'บัญชีนี้ใช้สิทธิ์ป้ายด่วนครบตามรอบเดือนนี้แล้ว',
    urgentQuotaUsedDetail: 'บัญชีนี้ใช้สิทธิ์ป้ายด่วนของรอบปัจจุบันครบแล้ว แต่ยังโพสต์และจัดการประกาศแบบปกติได้ตามปกติ',
    markedUrgent: 'ทำเครื่องหมายด่วนเรียบร้อยแล้ว',
    premiumPerkTitle: '🎁 สิทธิ์พิเศษ Premium',
    premiumPerkMessage: 'บัญชีนี้มีสิทธิ์ใช้ป้ายด่วนฟรี 1 ครั้งจาก Premium\\nเพื่อช่วยให้ประกาศถูกมองเห็นได้เร็วขึ้น\\n\\nต้องการใช้ตอนนี้หรือไม่?',
    useFreePerk: '🎁 ใช้สิทธิ์ฟรี',
    updateError: 'ไม่สามารถอัปเดตได้',
    markUrgentTitle: '⚡ ทำเครื่องหมายด่วน',
    markUrgentMessage: 'ช่วยให้ประกาศ "{title}" ถูกมองเห็นได้เร็วขึ้นเมื่อเปิดระบบชำระเงินในอนาคต',
    acknowledged: 'รับทราบ',
    freeTrialMode: 'ยังอยู่ในช่วงทดลองใช้ฟรี',
    freeTrialUrgentNote: 'ตอนนี้ระบบยังใช้งานฟรีอยู่ จึงยังไม่มีขั้นตอนชำระเงินจริงสำหรับป้ายด่วน',
    deletePostTitle: '🗑️ ลบประกาศ',
    deletePostMessage: 'คุณต้องการลบประกาศนี้ถาวรหรือไม่?\\nการดำเนินการนี้ไม่สามารถย้อนกลับได้',
    deletePermanently: 'ลบถาวร',
    postDeleted: 'ลบประกาศเรียบร้อยแล้ว',
    deletePostError: 'ไม่สามารถลบประกาศได้',
    extendPostTitle: '⏰ ต่ออายุประกาศ',
    extendPostMessage: 'ต่ออายุประกาศ "{title}" เพิ่มอีก 1 วัน',
    extendNow: 'ต่ออายุเลย',
    pleaseLogin: 'กรุณาเข้าสู่ระบบ',
    accountNotFound: 'ไม่พบข้อมูลบัญชีสำหรับใช้สิทธิ์',
    extendQuotaUsed: 'ใช้สิทธิ์ต่ออายุครบแล้ว',
    extendQuotaUsedReason: 'บัญชีนี้ใช้สิทธิ์ต่ออายุประกาศครบตามรอบเดือนนี้แล้ว',
    postExtended: 'ต่ออายุประกาศเพิ่มอีก 1 วันแล้ว',
    freeTrialExtendNote: 'ตอนนี้ระบบยังใช้งานฟรีอยู่ จึงยังไม่มีขั้นตอนชำระเงินจริงสำหรับการต่ออายุประกาศ',
    extendPostError: 'ไม่สามารถต่ออายุประกาศได้',
    startDateAsAgreed: 'เริ่มงานตามตกลง',
    workHoursAsAgreed: 'เวลางานตามตกลง',
    salary: 'เงินเดือน',
    compensation: 'ค่าตอบแทน',
    statusActive: 'กำลังเปิด',
    statusUrgent: 'ด่วน',
    statusClosed: 'ปิดแล้ว',
    statusExpired: 'หมดอายุ',
    statusDeleted: 'ถูกลบ',
    notSpecified: 'ไม่ระบุ',
    baht: 'บาท',
    perHour: 'ชม.',
    perDay: 'วัน',
    perMonth: 'เดือน',
    perShift: 'เวร',
    posted: 'โพสต์ ',
    expired: 'หมดอายุแล้ว',
    daysLeft: 'เหลือ {count} วัน',
    tapToManage: 'แตะเพื่อจัดการ',
    filterAll: 'ทั้งหมด',
    loginToViewPosts: 'เข้าสู่ระบบเพื่อดูประกาศของคุณ',
    login: 'เข้าสู่ระบบ',
    noPosts: 'ยังไม่มีประกาศ',
    noPostsDescription: 'คุณยังไม่ได้สร้างประกาศใดๆ ลองสร้างประกาศใหม่ดูสิ!',
    createPost: 'สร้างประกาศ',
    noPostsInFilter: 'ไม่มีประกาศในหมวดนี้',
    viewApplicants: 'ดูผู้สมัคร',
    edit: 'แก้ไข',
    extendPost: 'ต่ออายุประกาศ',
    markUrgent: 'ทำเครื่องหมายด่วน',
    reactivate: 'เปิดใหม่',
  },
  notifications: {
    title: 'การแจ้งเตือน',
    today: 'วันนี้',
    yesterday: 'เมื่อวาน',
    thisWeek: 'สัปดาห์นี้',
    error: 'เกิดข้อผิดพลาด',
    markAllReadError: 'ไม่สามารถอ่านทั้งหมดได้',
    deleteNotificationTitle: 'ลบการแจ้งเตือน',
    deleteNotificationMessage: 'ต้องการลบการแจ้งเตือนนี้หรือไม่?',
    cancel: 'ยกเลิก',
    delete: 'ลบ',
    deleteError: 'ไม่สามารถลบได้',
    unknownUser: 'ผู้ใช้',
    loginToView: 'เข้าสู่ระบบเพื่อดูการแจ้งเตือน',
    loginSubtitle: 'รับการแจ้งเตือนงานใหม่และข้อความ',
    login: 'เข้าสู่ระบบ',
    loading: 'กำลังโหลด...',
    markAllRead: 'อ่านทั้งหมด',
    empty: 'ไม่มีการแจ้งเตือน',
    emptySubtitle: 'เมื่อมีกิจกรรมใหม่ จะแสดงที่นี่',
  },
  payment: {
    transitionReviewTitle: 'ถึงช่วงทบทวนการเปิดชำระเงินแล้ว',
    monthlyQuotaTitle: 'ช่วงใช้งานแบบโควตารายเดือน',
    livePaymentTitle: 'ระบบชำระเงินจริงเริ่มทำงานแล้ว',
    transitionReviewDesc: 'ตอนนี้ระบบถึงเกณฑ์ทบทวนแล้ว แต่ยังคงใช้ฟรีต่อจนกว่าผู้ดูแลจะอนุมัติเปิดชำระเงินจริง',
    monthlyQuotaDesc: 'ตอนนี้แอปยังไม่เรียกเก็บเงินจริงในแอป โดยสิทธิ์ต่าง ๆ จะถูกควบคุมผ่านโควตารายเดือนของบัญชี',
    livePaymentDesc: 'สถานะนี้ใช้เมื่อผู้ดูแลอนุมัติเปิดชำระเงินจริงและช่องทางชำระเงินพร้อมใช้งานแล้ว',
    gatewayReadyAwaitingApproval: 'ช่องทางชำระเงินจริงพร้อมแล้ว แต่ระบบยังรอผู้ดูแลอนุมัติการเปิดใช้งาน',
    awaitingGateway: 'ระบบยังรอช่องทางชำระเงินจริงพร้อมก่อนเข้าสู่ขั้นพิจารณาเปิดใช้งานจริง',
    quotaManagedNote: 'สิทธิ์ฟีเจอร์หลักและบริการเสริมที่เปิดให้ จะถูกดูแลผ่านระบบโควตารายเดือนของบัญชีโดยตรง',
    noChargesNote: 'ไม่มีการจำลองชำระเงินและไม่มีการตัดเงินในขั้นตอนนี้',
    livePaymentReady: 'ระบบชำระเงินพร้อมและถูกเปิดใช้งานแล้วในสถานะนี้',
    paymentNotReady: 'ระบบชำระเงินยังไม่พร้อม จึงยังไม่สามารถเปิดเก็บเงินจริงได้',
    willNotifyBeforeLaunch: 'เมื่อเปิดระบบชำระเงิน เราจะแจ้งรายละเอียดให้ทราบก่อนใช้งานจริง',
    currentStatus: 'สถานะตอนนี้',
    activeAmount: 'จำนวนที่เปิดใช้งานอยู่',
    noCharges: 'ยังไม่คิดเงิน',
    baht: 'บาท',
    continueUsing: 'กลับไปใช้งานต่อ',
    closePage: 'ปิดหน้านี้',
  },
  favorites: {
    title: '❤️ รายการโปรด',
    noResults: 'ไม่พบผลลัพธ์',
    noSavedJobs: 'ยังไม่มีงานที่บันทึก',
    tryDifferentSearch: 'ลองเปลี่ยนคำค้นหาใหม่',
    tapToSave: 'กดไอคอน ❤️ เพื่อบันทึกงานที่สนใจ',
    perHour: '/ชม.',
    perDay: '/วัน',
    perMonth: '/เดือน',
    perShift: '/เวร',
    negotiable: 'ตามตกลง',
    postExpired: 'ประกาศหมดอายุแล้ว',
    urgent: '⚡ ด่วน',
    noFacility: 'ไม่ระบุสถานพยาบาล',
    removeTitle: 'ลบออกจากรายการโปรด',
    removeMessage: 'ต้องการลบ "{title}" ออกจากรายการโปรดหรือไม่?',
    cancel: 'ยกเลิก',
    remove: 'ลบออก',
    searchPlaceholder: 'ค้นหาชื่องาน, โรงพยาบาล, สถานที่...',
    loading: 'กำลังโหลด...',
    resultCount: 'พบ {filtered} จาก {total} รายการ',
  },
  map: {
    locationNotFoundTitle: 'ไม่พบตำแหน่ง',
    locationNotFoundMessage: 'กรุณาเปิดใช้ GPS แล้วลองใหม่',
    seeRate: 'ดูอัตรา',
    rateUnitShift: '/เวร',
    rateUnitHour: '/ชม',
    rateUnitDay: '/วัน',
    rateUnitMonth: '/เดือน',
    loading: 'กำลังโหลด...',
    jobsOnMap: '{count} งานบนแผนที่',
    searchPlaceholder: 'ค้นหาชื่องาน หรือชื่อสถานที่',
    searchChipLabel: 'ค้นหา: {term}',
    sortRateDesc: 'เรียง: ค่าจ้างสูงสุด',
    sortNearby: 'เรียง: ใกล้ฉัน',
    urgentOnly: 'ด่วนเท่านั้น',
    legendUrgent: 'ด่วน',
    loadingJobs: 'กำลังโหลดงาน...',
    jobFallbackTitle: 'งาน',
    urgentTag: '⚡ ด่วน',
    viewJob: 'ดูงาน',
    filterTitle: 'กรองงาน',
    filterReset: 'รีเซ็ต',
    filterPostType: 'ประเภทประกาศ',
    filterAll: 'ทั้งหมด',
    filterProvince: 'จังหวัด',
    filterStaffType: 'ประเภทบุคลากร',
    filterMinRate: 'ค่าตอบแทนขั้นต่ำ',
    filterSortBy: 'เรียงลำดับ',
    sortLatest: 'ล่าสุด',
    sortHighestPay: 'ค่าจ้างสูงสุด',
    sortNearMe: 'ใกล้ฉัน',
    filterStatus: 'สถานะ',
    filterUrgentOnly: '⚡ ด่วนเท่านั้น',
    filterApply: 'แสดง {count} รายการ',
    postTypeShift: 'หาคนแทนเวร',
    postTypeJob: 'รับสมัครงาน',
    postTypeHomecare: 'ดูแลผู้ป่วย',
  },
  help: {
    headerTitle: 'ช่วยเหลือ',
    searchPlaceholder: 'ค้นหาคำถาม...',
    allCategories: 'ทั้งหมด',
    faqSectionTitle: 'คำถามที่พบบ่อย',
    emptySearch: 'ไม่พบคำถามที่ตรงกับการค้นหา',
    contactTitle: 'ติดต่อเรา',
    contactSubtitle: 'ยังหาคำตอบไม่เจอ? ติดต่อทีมสนับสนุนของเรา',
    contactEmail: 'อีเมล',
    contactPhone: 'โทรศัพท์',
    officeHours: 'เวลาทำการ: จันทร์ - ศุกร์ 9:00 - 18:00 น.',
    emailSubject: 'ขอความช่วยเหลือ',
    onboardingGuideLink: 'ดูคู่มือเริ่มต้นใช้งาน',
    termsLink: 'ข้อกำหนดการใช้งาน',
    privacyLink: 'นโยบายความเป็นส่วนตัว',
    aboutLink: 'เกี่ยวกับเรา',
    quickLinksTitle: 'ลิงก์ที่เกี่ยวข้อง',
    catGeneral: 'ทั่วไป',
    catAccount: 'บัญชี',
    catJobs: 'งาน',
    catApplications: 'การสมัคร',
    catHospital: 'โรงพยาบาล',
    catPayment: 'การชำระเงิน',
    faq1Q: 'NurseGo คืออะไร?',
    faq1A: 'NurseGo เป็นแพลตฟอร์มช่วยหางานสำหรับพยาบาลและบุคลากรทางการแพทย์ ช่วยเชื่อมต่อผู้หางานเข้ากับโรงพยาบาล คลินิก และเอเจนซี่ได้อย่างรวดเร็วและสะดวก',
    faq2Q: 'แอปนี้ใช้งานฟรีหรือไม่?',
    faq2A: 'ตอนนี้แอปอยู่ในช่วงทดลองใช้ฟรี เมื่อเปิดระบบชำระเงินจริง เราจะแจ้งผู้ใช้ทุกท่านก่อนเรียกเก็บค่าบริการ',
    faq3Q: 'รองรับการใช้งานบนอุปกรณ์อะไรบ้าง?',
    faq3A: 'NurseGo รองรับสมาร์ทโฟนและแท็บเล็ตทั้ง iOS และ Android',
    faq4Q: 'จะสมัครสมาชิกได้อย่างไร?',
    faq4A: 'กดปุ่ม "สมัครสมาชิก" ที่หน้าเข้าสู่ระบบ แล้วทำตามขั้นตอน—กรอกเบอร์โทรหรืออีเมล ยืนยันตัวตน เลือกบทบาท และตั้งค่าโปรไฟล์',
    faq5Q: 'ลืมรหัสผ่านทำอย่างไร?',
    faq5A: 'กด "ลืมรหัสผ่าน" ที่หน้าเข้าสู่ระบบ แล้วกรอกอีเมลที่ลงทะเบียนไว้ ระบบจะส่งลิงก์รีเซ็ตรหัสผ่านให้',
    faq6Q: 'จะแก้ไขข้อมูลโปรไฟล์ได้อย่างไร?',
    faq6A: 'ไปที่แท็บโปรไฟล์ กดไอคอนแก้ไข แล้วอัปเดตข้อมูลของคุณ',
    faq7Q: 'จะลบบัญชีได้อย่างไร?',
    faq7A: 'ไปที่ตั้งค่า > เลื่อนลง > "ลบบัญชี" ข้อมูลทั้งหมดจะถูกลบถาวร',
    faq8Q: 'จะค้นหางานที่ตรงใจได้อย่างไร?',
    faq8A: 'ใช้ช่องค้นหาและตัวกรองในหน้าแรก กรองได้ตามสถานที่ ประเภทบุคลากร ค่าตอบแทน และอื่นๆ',
    faq9Q: 'บันทึกงานที่สนใจได้อย่างไร?',
    faq9A: 'กดไอคอน ❤️ บนการ์ดงานเพื่อบันทึกไว้ในรายการโปรด',
    faq10Q: 'งานที่แสดงมาจากไหน?',
    faq10A: 'งานถูกโพสต์โดยโรงพยาบาล คลินิก เอเจนซี่ และบุคคลทั่วไปที่ต้องการหาบุคลากรทางการแพทย์',
    faq11Q: 'จะสมัครงานได้อย่างไร?',
    faq11A: 'เปิดงานที่สนใจแล้วกดปุ่ม "สนใจงานนี้" หรือ "Quick Apply" ด้านล่าง',
    faq12Q: 'จะดูสถานะการสมัครได้ที่ไหน?',
    faq12A: 'ไปที่แท็บข้อความเพื่อดูการสนทนากับผู้โพสต์ หรือตรวจสอบการสมัครล่าสุดในแท็บการแจ้งเตือน',
    faq13Q: 'สามารถยกเลิกการสมัครได้ไหม?',
    faq13A: 'ปัจจุบันยังไม่สามารถยกเลิกได้หลังจากแสดงความสนใจ คุณสามารถแจ้งผู้โพสต์ผ่านแชทได้หากเปลี่ยนแปลนง',
    faq14Q: 'ต้องอัปโหลดเอกสารอะไรบ้าง?',
    faq14A: 'อัปโหลดใบประกอบวิชาชีพ บัตรประชาชน และใบรับรองที่เกี่ยวข้อง เพื่อเพิ่มความน่าเชื่อถือ',
    faq15Q: 'โรงพยาบาลจะลงประกาศงานได้อย่างไร?',
    faq15A: 'เลือกบทบาท "โรงพยาบาล / คลินิก / เอเจนซี่" ตั้งค่าโปรไฟล์ให้เรียบร้อย แล้วกดปุ่ม "+" ที่แท็บโพสต์',
    faq16Q: 'จะดูผู้สมัครได้ที่ไหน?',
    faq16A: 'เปิดประกาศจาก "ประกาศของฉัน" แล้วกด "ดูผู้สมัคร" เพื่อเห็นผู้สนใจทั้งหมด',
    faq17Q: 'รีวิวของโรงพยาบาลมีผลอย่างไร?',
    faq17A: 'รีวิวช่วยให้พยาบาลประเมินสถานที่ทำงาน และช่วยโรงพยาบาลสร้างความน่าเชื่อถือกับผู้สมัคร',
    faq18Q: 'โรงพยาบาลต้องจ่ายค่าธรรมเนียมอะไรบ้าง?',
    faq18A: 'ตอนนี้แอปใช้งานฟรีสำหรับทุกคนในช่วงเปิดตัว เมื่อเปิดระบบชำระเงิน รายละเอียดค่าบริการจะประกาศล่วงหน้า',
    faq19Q: 'ชำระเงินได้ทางช่องทางไหนบ้าง?',
    faq19A: 'ช่องทางชำระเงินจะประกาศเมื่อระบบชำระเงินพร้อมใช้งาน',
    faq20Q: 'ขอใบเสร็จได้อย่างไร?',
    faq20A: 'การออกใบเสร็จจะพร้อมใช้งานเมื่อเปิดระบบชำระเงินจริง สอบถามเพิ่มเติมที่ฝ่ายสนับสนุน',
  },
  reviews: {
    userFallback: 'ผู้ใช้งาน',
    workplaceFallback: 'สถานที่ทำงาน',
    alertNotice: 'แจ้งเตือน',
    alreadyReviewedJob: 'คุณได้รีวิวงานนี้แล้ว',
    alreadyReviewedPlace: 'คุณได้รีวิวสถานที่นี้แล้ว',
    cannotReviewTitle: 'ยังรีวิวไม่ได้',
    cannotReviewMessage: 'จะรีวิวได้เมื่อมีงานที่ยืนยันแล้วและจบงานเรียบร้อย',
    validationTitle: 'กรุณากรอกข้อมูล',
    validationTitleRequired: 'กรุณาใส่หัวข้อรีวิว',
    validationContentRequired: 'กรุณาใส่เนื้อหารีวิว',
    successTitle: 'สำเร็จ',
    successMessage: 'ขอบคุณสำหรับรีวิวของคุณ',
    errorTitle: 'เกิดข้อผิดพลาด',
    errorSubmitFallback: 'ไม่สามารถส่งรีวิวได้',
    loginTitle: 'กรุณาเข้าสู่ระบบ',
    loginHelpfulMessage: 'เข้าสู่ระบบก่อนกดว่ารีวิวนี้มีประโยชน์',
    alreadyHelpfulTitle: 'กดแล้ว',
    alreadyHelpfulMessage: 'คุณกดว่ารีวิวนี้มีประโยชน์ไปแล้ว',
    helpfulErrorTitle: 'กดไม่ได้',
    helpfulErrorFallback: 'ไม่สามารถบันทึกคะแนนประโยชน์ได้',
    noUserData: 'ไม่พบข้อมูลผู้ใช้งาน',
    noWorkplaceData: 'ไม่พบข้อมูลสถานที่ทำงาน',
    goBack: 'กลับ',
    loading: 'กำลังโหลดรีวิว...',
    verified: 'ยืนยันแล้ว',
    recommend: 'แนะนำ',
    notRecommend: 'ไม่แนะนำ',
    helpfulDone: 'มีประโยชน์แล้ว',
    helpful: 'มีประโยชน์',
    report: 'รายงานรีวิว',
    responseFromUser: 'คำตอบจากผู้ใช้งาน',
    responseFromWorkplace: 'คำตอบจากสถานที่ทำงาน',
    headerSubtitle: 'รีวิว',
    ratingCount: 'รีวิว',
    writeReview: 'เขียนรีวิว',
    reviewHint: 'รีวิวได้เมื่อคุณมีงานที่ยืนยันแล้วและจบงานกับโปรไฟล์นี้',
    sortLatest: 'ล่าสุด',
    sortHighest: 'คะแนนมากสุด',
    sortLowest: 'คะแนนน้อยสุด',
    sortMostHelpful: 'มีประโยชน์มากสุด',
    sortLeastHelpful: 'มีประโยชน์น้อยสุด',
    emptyTitle: 'ยังไม่มีรีวิว',
    emptySubtitleUser: 'เป็นคนแรกที่รีวิวผู้ใช้งานนี้',
    emptySubtitlePlace: 'เป็นคนแรกที่รีวิวสถานที่นี้',
    submitting: 'กำลังส่ง...',
    submit: 'ส่ง',
    rateLabel: 'ให้คะแนน',
    titleLabel: 'หัวข้อ *',
    titlePlaceholder: 'เช่น ประสบการณ์ทำงานที่ดี',
    detailsLabel: 'รายละเอียด *',
    detailsPlaceholder: 'บอกเล่าประสบการณ์ของคุณ...',
    prosLabel: 'ข้อดี',
    prosPlaceholder: 'สิ่งที่ชอบ...',
    consLabel: 'ข้อเสีย',
    consPlaceholder: 'สิ่งที่ควรปรับปรุง...',
    recommendQuestion: 'คุณจะแนะนำให้ผู้อื่นหรือไม่?',
  },
  verification: {
    error: 'ข้อผิดพลาด',
    firstNameRequired: 'กรุณากรอกชื่อจริง',
    lastNameRequired: 'กรุณากรอกนามสกุล',
    licenseNumberRequired: 'กรุณากรอกเลขที่ใบอนุญาต',
    licenseInvalidFormat: 'รูปแบบเลขใบอนุญาตไม่ถูกต้อง',
    licenseDocRequired: 'กรุณาอัปโหลดใบประกอบวิชาชีพ',
    employeeCardRequired: 'กรุณาอัปโหลดบัตรพนักงาน',
    idCardRequired: 'กรุณาอัปโหลดบัตรประชาชน',
    declarationRequired: 'กรุณาอัปโหลดเอกสารเซ็นกำกับว่าใช้กับ NurseGo',
    incompleteTitle: 'ข้อมูลไม่ครบ',
    noNameFallback: 'ไม่ระบุชื่อ',
    submitSuccessTitle: 'ส่งคำขอสำเร็จ',
    submitSuccessMessage: 'คำขอยืนยันตัวตนของคุณถูกส่งแล้ว ทีมงานจะตรวจสอบภายใน 1-3 วันทำการ',
    submitErrorFallback: 'ไม่สามารถส่งคำขอยืนยันตัวตนได้',
    tapToUpload: 'แตะเพื่ออัปโหลด',
    loading: 'กำลังโหลด...',
    verificationType: 'ประเภทการยืนยัน',
    licenseType: 'ประเภทใบอนุญาต',
    documentNumber: 'เลขที่เอกสาร',
    pendingTitle: 'รอการตรวจสอบ',
    pendingMessage: 'คำขอยืนยันตัวตนของคุณอยู่ระหว่างการตรวจสอบ ทีมงานจะตรวจสอบภายใน 1-3 วันทำการ',
    applicantName: 'ชื่อผู้ยื่น',
    tagsFromSurvey: 'Tag จาก role / survey',
    applicantInfoTitle: 'ข้อมูลผู้ยื่นคำขอ',
    firstName: 'ชื่อจริง',
    firstNamePlaceholder: 'กรอกชื่อจริง',
    lastName: 'นามสกุล',
    lastNamePlaceholder: 'กรอกนามสกุล',
    licenseInfoTitle: 'ข้อมูลใบอนุญาต',
    licenseNumber: 'เลขที่ใบอนุญาต',
    licenseNumberPlaceholder: 'เช่น ว.12345',
    selectType: 'เลือกประเภท',
    licenseExpiry: 'วันหมดอายุใบอนุญาต',
    documentsTitle: 'เอกสารประกอบ',
    licenseDocLabel: 'ใบประกอบวิชาชีพ',
    licenseDocDesc: 'อัปโหลดรูปใบประกอบวิชาชีพที่ใช้ตรวจสอบ',
    employeeCardLabel: 'บัตรพนักงาน / เอกสารสังกัด',
    employeeCardDesc: 'ใช้ยืนยันว่าคุณเป็นผู้แทนของหน่วยงานนี้จริง',
    idCardLabel: 'บัตรประชาชน',
    idCardDesc: 'อัปโหลดเฉพาะข้อมูลที่ใช้ยืนยันตัวตนได้ชัดเจน',
    declarationLabel: 'เอกสารเซ็นกำกับว่าใช้กับ NurseGo',
    declarationDesc: 'กรุณาอัปโหลดเอกสารเซ็นกำกับการใช้งานกับ NurseGo',
    privacyNote: 'เอกสารทั้งหมดใช้เพื่อการตรวจสอบตัวตนและความน่าเชื่อถือของผู้โพสต์งานเท่านั้น',
    submitting: 'กำลังส่ง...',
    submitButton: 'ส่งคำขอยืนยัน',
    selectLicenseTypeTitle: 'เลือกประเภทใบอนุญาต',
    selectImageTitle: 'เลือกรูปเอกสาร',
    pickFromGallery: 'เลือกจากคลังรูปภาพ',
    takePhoto: 'ถ่ายรูป',
  },
  documents: {
    headerTitle: 'เอกสารของฉัน',
    errorSelectDoc: 'ไม่สามารถเลือกเอกสารได้',
    permissionTitle: 'ต้องการสิทธิ์',
    permissionMessage: 'กรุณาอนุญาตการเข้าถึงรูปภาพ',
    errorSelectImage: 'ไม่สามารถเลือกรูปภาพได้',
    fileTooLargeTitle: 'ไฟล์ใหญ่เกินไป',
    fileTooLargeMessage: 'ขนาดไฟล์สูงสุด 10MB',
    uploadSuccessTitle: 'สำเร็จ',
    uploadSuccessMessage: 'อัพโหลดเอกสารเรียบร้อยแล้ว',
    uploadErrorMessage: 'ไม่สามารถอัพโหลดได้ กรุณาลองใหม่',
    cancelRequest: 'ยกเลิกคำขอ',
    deleteDocument: 'ลบเอกสาร',
    confirmCancelRequest: 'ต้องการยกเลิกคำขอสำหรับ "{name}" หรือไม่?',
    confirmDelete: 'ต้องการลบ "{name}" หรือไม่?',
    cancel: 'ยกเลิก',
    confirm: 'ยืนยัน',
    delete: 'ลบ',
    deleteError: 'ไม่สามารถลบได้',
    statusApproved: 'อนุมัติแล้ว',
    statusRejected: 'ไม่ผ่านการตรวจสอบ',
    statusPending: 'รอการตรวจสอบ',
    loginTitle: 'เข้าสู่ระบบเพื่อจัดการเอกสาร',
    loginSubtitle: 'อัพโหลด Resume, ใบประกอบวิชาชีพ และเอกสารอื่นๆ',
    loginButton: 'เข้าสู่ระบบ',
    loading: 'กำลังโหลด...',
    uploading: 'กำลังอัพโหลด...',
    addDocument: 'เพิ่มเอกสาร',
    emptyTitle: 'ยังไม่มีเอกสาร',
    emptySubtitle: 'เพิ่มเอกสารเพื่อเพิ่มโอกาสในการสมัครงาน',
    selectTypeTitle: 'เลือกประเภทเอกสาร',
    viewDocumentFallback: 'ดูเอกสาร',
    statusLabel: 'สถานะ:',
    rejectionReasonLabel: 'เหตุผลที่ไม่ผ่าน:',
    rejectionInline: 'เหตุผล:',
    error: 'เกิดข้อผิดพลาด',
  },
  feedback: {
    headerTitle: 'Feedback & รีวิว',
    loginTitle: 'กรุณาเข้าสู่ระบบ',
    loginMessage: 'คุณต้องเข้าสู่ระบบก่อนส่ง feedback',
    validationTitle: 'กรุณากรอกข้อมูล',
    titleRequired: 'กรุณากรอกหัวข้อ',
    messageRequired: 'กรุณากรอกข้อความ',
    userFallback: 'ผู้ใช้',
    successTitle: 'ส่ง Feedback สำเร็จ',
    successMessage: 'ขอบคุณสำหรับความคิดเห็นของคุณ เราจะนำไปปรับปรุงแอพให้ดียิ่งขึ้น',
    errorTitle: 'ข้อผิดพลาด',
    rating1: 'แย่มาก 😢',
    rating2: 'ไม่ดี 😕',
    rating3: 'ปานกลาง 😐',
    rating4: 'ดี 😊',
    rating5: 'ยอดเยี่ยม 🤩',
    historyTitle: 'ประวัติ Feedback ของคุณ',
    emptyHistory: 'ยังไม่มี feedback',
    adminResponseLabel: '📢 ตอบกลับจากทีมงาน:',
    limitText: 'คุณส่ง feedback ไปแล้ววันนี้\\nกรุณารอพรุ่งนี้',
    rateTitle: 'ให้คะแนนแอพของเรา',
    typeTitle: 'ประเภท Feedback',
    messageTitle: 'ข้อความของคุณ',
    titlePlaceholder: 'หัวข้อ',
    messagePlaceholder: 'รายละเอียด... (บอกเราว่าคุณชอบอะไร หรืออยากให้ปรับปรุงอะไร)',
    submitButton: '📤 ส่ง Feedback',
    disclaimer: 'Feedback ของคุณจะช่วยให้เราพัฒนาแอพให้ดียิ่งขึ้น\\nทีมงานจะอ่านทุกข้อความ 💙',
  },
  privacy: {
    headerTitle: 'นโยบายความเป็นส่วนตัว',
    emailSubject: 'คำถามเกี่ยวกับข้อมูลส่วนบุคคล',
    lastUpdated: 'อัปเดตล่าสุด:',
    introTitle: 'ความเป็นส่วนตัวของคุณสำคัญสำหรับเรา',
    introText: 'NurseGo มุ่งมั่นปกป้องข้อมูลส่วนบุคคลของคุณ นโยบายนี้อธิบายว่าเราเก็บข้อมูลอะไร ใช้อย่างไร และสิทธิ์ของคุณเกี่ยวกับข้อมูลส่วนบุคคล',
    summaryTitle: 'สรุปสั้นๆ',
    summary1: 'เราเก็บข้อมูลเท่าที่จำเป็นต่อการให้บริการ',
    summary2: 'ข้อมูลของคุณได้รับการเข้ารหัสและปกป้อง',
    summary3: 'เราไม่ขายข้อมูลของคุณให้บุคคลภายนอก',
    summary4: 'คุณสามารถลบบัญชีและข้อมูลได้ตลอดเวลา',
    contactTitle: 'มีคำถามเกี่ยวกับความเป็นส่วนตัว?',
    contactSubtitle: 'ติดต่อเราเพื่อสอบถามหรือใช้สิทธิ์เกี่ยวกับข้อมูลส่วนบุคคล',
    footerCopyright: '© 2569 NurseGo. สงวนลิขสิทธิ์.',
    footerNote: 'หากในอนาคตมีเว็บไซต์หรือบริการใหม่เพิ่มเติม นโยบายที่เกี่ยวข้องอาจมีการปรับปรุงเพิ่มเติม โดยจะแจ้งผู้ใช้ผ่านช่องทางที่เหมาะสม',
  },
  terms: {
    headerTitle: 'ข้อกำหนดการใช้งาน',
    lastUpdated: 'อัปเดตล่าสุด:',
    introText: 'กรุณาอ่านข้อกำหนดการใช้งานฉบับนี้อย่างละเอียด การใช้งาน NurseGo ถือว่าคุณยอมรับข้อกำหนดเหล่านี้',
    footerCopyright: '© 2569 NurseGo. สงวนลิขสิทธิ์.',
  },
  shop: {
    trialTitle: 'ยังอยู่ในช่วงทดลองใช้ฟรี',
    trialMessage: '{subject} จะเปิดให้ใช้งานเมื่อระบบชำระเงินพร้อม ตอนนี้ยังไม่มีค่าใช้จ่าย',
    launchAccessTitle: 'ตอนนี้ยังเป็นสิทธิ์ช่วงเปิดตัว',
    launchAccessMessage: 'แพ็กเกจ {name} ยังไม่เปิดเก็บเงินจริง คุณใช้งานได้ตามโควตารายเดือน',
    loginWarning: 'กรุณาเข้าสู่ระบบ',
    addonLaunchMessage: 'บริการเสริมนี้ยังไม่เปิดเก็บเงินจริง ฟีเจอร์ดูแลผ่านโควตารายเดือน',
    addonExtraPost: 'โพสต์เพิ่ม',
    addonExtendPost: 'ต่ออายุโพสต์',
    addonUrgent: 'ปุ่มด่วน',
    codeCopiedTitle: '📋 คัดลอกแล้ว!',
    codeCopiedMessage: 'โค้ด {code} ถูกคัดลอกแล้ว',
    clearCodeSuccessTitle: 'ลบโค้ดที่รอใช้แล้ว',
    clearCodeSuccessMessage: 'คุณสามารถกลับไปกรอกโค้ดใหม่ที่หน้าโปรไฟล์ได้',
    clearCodeErrorTitle: 'ลบโค้ดไม่สำเร็จ',
    clearCodeErrorMessage: 'กรุณาลองใหม่',
    errorTitle: '❌ เกิดข้อผิดพลาด',
    headerTitleFree: 'สิทธิ์และบริการในบัญชี',
    headerTitlePaid: 'สิทธิ์และแพ็กเกจ',
    freeAccessTitle: 'สิทธิ์เพิ่มเติมที่เปิดใช้ในบัญชีนี้',
    freeAccessDesc: 'บัญชีนี้ใช้งานฟีเจอร์หลักและบริการเสริมได้ในช่วงเปิดตัว ดูแลผ่านโควตารายเดือน',
    freeAccessHint: 'รายละเอียดที่เห็นอาจแตกต่างกันตามประเภทบัญชีและแพ็กเกจ',
    currentPlanLabel: 'แพ็กเกจปัจจุบัน',
    pendingCodeTitle: 'โค้ดที่รอใช้',
    clearButton: 'ล้าง',
    discountSummary: 'จาก ฿{from} เหลือ ฿{to}',
    pendingCodeHint: 'ระบบจะใช้โค้ดนี้อัตโนมัติเมื่อซื้อรายการที่ตรงกัน',
    sectionAccessTitle: 'สิทธิ์ที่เปิดใช้ในบัญชีนี้',
    monthly: 'รายเดือน',
    annual: 'รายปี',
    savingsHint: 'ประหยัด ~17%',
    nursePlansTitle: 'แพ็กเกจสำหรับพยาบาล',
    hospitalPlansTitle: 'แพ็กเกจสำหรับโรงพยาบาล',
    addonsTitle: 'บริการเสริมที่พร้อมใช้ในบัญชีนี้',
    addonsTitlePaid: 'เปิดใช้รายครั้ง',
    extraPostTitle: 'โพสต์เพิ่ม 1 ครั้ง',
    extraPostDesc: 'ใช้สำหรับเพิ่มความยืดหยุ่นเมื่อโควตาโพสต์ประจำเดือนใกล้เต็ม',
    seeQuota: 'ดูโควตาในบัญชี',
    extendPostTitle: 'ต่ออายุโพสต์ +1 วัน',
    extendPostDesc: 'ขยายเวลาให้ประกาศยังมองเห็นต่อได้ตามโควตาบริการเสริม',
    urgentTitle: 'ปุ่มด่วน (Urgent)',
    urgentDesc: 'ช่วยให้ประกาศสำคัญถูกมองเห็นได้เร็วขึ้นตามโควตาบริการเสริม',
    referralTitle: 'แนะนำเพื่อน',
    referralHeadline: 'แนะนำเพื่อน → ได้ Pro ฟรี 1 เดือน!',
    referralDesc: 'เพื่อนสมัครและอัปเกรด คุณและเพื่อนได้รับสิทธิ์พรีเมียมฟรี 1 เดือน',
    referralCodeLabel: 'โค้ดของคุณ',
    copyButton: 'คัดลอก',
    statReferred: 'เพื่อนที่แนะนำ',
    statFreeMonths: 'เดือนฟรีที่ได้',
    statMonthsLeft: 'เดือนคงเหลือ',
    savingsPercent: 'ประหยัด {savings}%',
    currentTag: 'ใช้งานอยู่',
    upgradeButton: 'อัพเกรด',
    includedInAccount: 'รวมในสิทธิ์บัญชีนี้',
    perYear: '/ปี',
    perMonth: '/เดือน',
    selectPlan: 'เลือกแผนนี้',
    audienceFree: 'เหมาะกับคนที่เพิ่งเริ่มใช้งานและยังลงประกาศไม่บ่อย',
    audiencePremium: 'คุ้มกับผู้ใช้ทั่วไปที่ต้องการสิทธิ์ใช้งานมากขึ้น',
    audienceNursePro: 'คุ้มกับพยาบาลที่ลงเวรหรือหางานต่อเนื่องทุกสัปดาห์',
    audienceHospitalStarter: 'คุ้มกับองค์กรที่ลงประกาศเป็นรอบ',
    audienceHospitalPro: 'คุ้มกับองค์กรที่เปิดรับหลายตำแหน่งต่อเนื่อง',
    audienceHospitalEnterprise: 'คุ้มกับองค์กรที่ต้องดันประกาศหลายชิ้นพร้อมกันตลอดเดือน',
    hospitalFeature1: 'ลงประกาศและติดตามผู้สมัครภายในโควตารายเดือน',
    hospitalFeature2: 'จัดการประกาศด้วยเครื่องมือ ปิด ต่ออายุ และด่วน',
    hospitalFeature3: 'แชทกับผู้สนใจได้โดยตรง',
    consumerFeature1: 'ใช้งานฟีเจอร์หลักภายในโควตารายเดือน',
    consumerFeature2: 'บันทึกงานโปรดและรับการแจ้งเตือน',
    consumerFeature3: 'แชทกับผู้โพสต์และจัดการเอกสาร',
  },
  chooseRole: {
    title: 'คุณเป็นใคร?',
    subtitle: 'เลือกบทบาทเพื่อประสบการณ์ที่เหมาะกับคุณ',
    stepLabel: 'ขั้นตอนที่ 2 / 3',
    nurseTitle: 'พยาบาล / บุคลากรทางการแพทย์',
    nurseSubtitle: 'กำลังมองหางานเวร, งานพาร์ทไทม์',
    nurseBullet1: 'ค้นหางานเวร / งานพาร์ทไทม์',
    nurseBullet2: 'แจ้งเตือนงานใกล้ตัวอัตโนมัติ',
    nurseBullet3: 'แสดงใบประกอบวิชาชีพได้',
    hospitalTitle: 'โรงพยาบาล / คลินิก / เอเจนซี่',
    hospitalSubtitle: 'ต้องการโพสต์หาบุคลากร',
    hospitalBullet1: 'โพสต์งานหาพยาบาล / CG',
    hospitalBullet2: 'จัดการผู้สมัครได้',
    hospitalBullet3: 'ดูสถิติ + ประวัติผู้สมัคร',
    userTitle: 'คนทั่วไป / ญาติผู้ป่วย',
    userSubtitle: 'กำลังหาคนดูแลผู้ป่วยที่บ้าน',
    userBullet1: 'หาผู้ดูแลผู้ป่วย / เฝ้าไข้',
    userBullet2: 'ดูรีวิว + ตรวจสอบตัวตนได้',
    userBullet3: 'แชทกับผู้ดูแลได้โดยตรง',
    staffRN: 'RN — พยาบาลวิชาชีพ',
    staffPN: 'PN — พยาบาลเทคนิค',
    staffNA: 'NA — ผู้ช่วยพยาบาล',
    staffANES: 'ANES — วิสัญญีพยาบาล',
    staffCG: 'CG — ผู้ดูแลผู้ป่วย',
    staffSitter: 'เฝ้าไข้',
    staffOther: 'อื่นๆ',
    orgPublic: 'โรงพยาบาลรัฐ',
    orgPrivate: 'โรงพยาบาลเอกชน',
    orgClinic: 'คลินิก',
    orgAgency: 'เอเจนซี่จัดหางาน',
    userNotFound: 'ไม่พบผู้ใช้ที่เข้าสู่ระบบ',
    errorTitle: 'เกิดข้อผิดพลาด',
    errorSave: 'ไม่สามารถบันทึกได้ กรุณาลองใหม่',
    staffTypeLabel: 'คุณเป็นบุคลากรประเภทไหน?',
    optional: '(ไม่บังคับ)',
    orgTypeLabel: 'ประเภทองค์กรของคุณ?',
    saving: 'กำลังบันทึก...',
    continue: 'ดำเนินการต่อ',
    skip: 'ข้ามไปก่อน',
  },
  onboarding: {
    workFulltime: 'ประจำ / เต็มเวลา',
    workParttime: 'พาร์ทไทม์ / ชั่วคราว',
    workWeekend: 'เฉพาะวันหยุด / เสาร์-อาทิตย์',
    workFlexible: 'ยืดหยุ่น / รับทุกรูปแบบ',
    careElderly: 'ดูแลผู้สูงอายุทั่วไป',
    careBedridden: 'ดูแลผู้ป่วยติดเตียง',
    carePostSurg: 'ดูแลหลังผ่าตัด / พักฟื้น',
    careChild: 'ดูแลเด็ก / เด็กป่วย',
    careTerminal: 'ดูแลผู้ป่วยระยะท้าย',
    careOther: 'อื่นๆ',
    urgencyNow: 'เร่งด่วนมาก',
    urgencyWeek: 'ภายใน 1 สัปดาห์',
    urgencyMonth: 'ภายใน 1 เดือน',
    urgencyPlan: 'วางแผนล่วงหน้า',
    step1Title: 'เริ่มใช้งานได้คล่องในไม่กี่นาที',
    step1Subtitle: 'สรุปให้ว่าบทบาทของคุณทำอะไรได้บ้าง และฟีเจอร์หลักอยู่ตรงไหน',
    step2Title: 'ฟีเจอร์หลักอยู่ตรงไหน',
    step2Subtitle: 'ดูทางลัดของแอปก่อนเริ่มใช้งานจริง',
    step3Title: 'ปรับแอปให้ตรงกับคุณ',
    step3Subtitle: 'เลือกข้อมูลพื้นฐานเพื่อให้ระบบแนะนำงานหรือผู้ดูแลได้ตรงกับคุณมากขึ้น',
    badgeNurse: 'สำหรับพยาบาล',
    heroNurse: 'หางานไว คุยสะดวก และจัดการโปรไฟล์ได้ในที่เดียว',
    heroNurseSubtitle: 'NurseGo จะช่วยเรียงงานที่เหมาะกับความถนัดและพื้นที่ที่คุณสนใจ',
    nurseHighlight1: 'หางานแทนเวรได้ไว',
    nurseHighlight2: 'คุยกับผู้โพสต์ได้ต่อเนื่อง',
    nurseHighlight3: 'เพิ่มความมั่นใจให้โปรไฟล์',
    nurseFeature1: 'หน้าแรก',
    nurseFeature2: 'โพสต์',
    nurseFeature3: 'ข้อความ',
    nurseFeature4: 'โปรไฟล์',
    nurseSetupTitle: 'บอกเราว่าคุณทำงานแบบไหน',
    nurseSetupSubtitle: 'ข้อมูลนี้ช่วยให้แอปกรองงานได้แม่นขึ้นตั้งแต่ครั้งแรก',
    badgeHospital: 'สำหรับองค์กร',
    heroHospital: 'โพสต์รับสมัคร ดูผู้สนใจ และคุยต่อได้ในที่เดียว',
    heroHospitalSubtitle: 'บทบาทองค์กรจะโฟกัสที่การลงประกาศอย่างเป็นระบบและจัดการผู้สมัคร',
    hospitalHighlight1: 'ลงประกาศได้รวดเร็ว',
    hospitalHighlight2: 'ดูผู้สมัครเป็นระเบียบ',
    hospitalHighlight3: 'แชทได้ทันที',
    hospitalFeature1: 'หน้าแรก',
    hospitalFeature2: 'โพสต์',
    hospitalFeature3: 'ข้อความ',
    hospitalFeature4: 'โปรไฟล์',
    hospitalSetupTitle: 'ตั้งค่าพื้นฐานขององค์กร',
    hospitalSetupSubtitle: 'ระบุจังหวัดและความเร่งด่วน เพื่อให้ระบบแนะนำได้ดีขึ้น',
    badgeUser: 'สำหรับผู้ใช้งานทั่วไป',
    heroUser: 'ค้นหาผู้ดูแลที่เหมาะสม ติดต่ออย่างเป็นส่วนตัว และตัดสินใจได้มั่นใจ',
    heroUserSubtitle: 'แอปจะช่วยให้คุณหาผู้ดูแลที่ตรงประเภทงานและพื้นที่',
    userHighlight1: 'ดูประกาศที่ตรงกับคุณ',
    userHighlight2: 'ดูโปรไฟล์ก่อนตัดสินใจ',
    userHighlight3: 'ติดต่อผ่านช่องทางที่สะดวก',
    userFeature1: 'หน้าแรก',
    userFeature2: 'โพสต์',
    userFeature3: 'ข้อความ',
    userFeature4: 'โปรไฟล์',
    userSetupTitle: 'บอกประเภทการดูแลที่คุณสนใจ',
    userSetupSubtitle: 'เราจะแสดงผู้ดูแลที่ตรงกับความต้องการของคุณ',
    noticeText: 'ทุกขั้นตอนข้ามได้ และกลับมาดูใหม่ได้จากหน้า Settings',
    quickActionsTitle: 'เริ่มจาก 3 อย่างนี้ จะใช้งานได้คล่องขึ้นทันที',
    nurseQuick1: '1. เปิดงานใกล้คุณ เพื่อรู้ไวเมื่อมีเวรใหม่ในพื้นที่ที่สนใจ',
    nurseQuick2: '2. ยืนยันตัวตน เพื่อให้ผู้จ้างมั่นใจและตัดสินใจได้เร็วขึ้น',
    nurseQuick3: '3. เติมโปรไฟล์และรีวิวให้ครบ เพื่อให้โอกาสงานเข้าหาคุณง่ายขึ้น',
    hospitalQuick1: '1. เติมข้อมูลองค์กรในโปรไฟล์',
    hospitalQuick2: '2. สร้างประกาศแรกจากแท็บโพสต์',
    hospitalQuick3: '3. ติดตามผู้สมัครจาก Applicants และแชท',
    userQuick1: '1. ค้นหาผู้ดูแลจากหน้าแรกก่อน',
    userQuick2: '2. ดูโปรไฟล์และรีวิวก่อนติดต่อ',
    userQuick3: '3. บันทึกประกาศที่สนใจไว้เปรียบเทียบ',
    staffTypeTitle: 'ประเภทวิชาชีพของคุณ',
    staffTypeSubtitle: 'เลือกได้หลายประเภท หากคุณทำงานได้มากกว่าหนึ่งสาย',
    provinceTitle: 'จังหวัดที่ใช้งานบ่อย',
    provinceSubtitle: 'ใช้สำหรับตั้งต้นการค้นหาและช่วยให้ผลลัพธ์ตรงพื้นที่มากขึ้น',
    provinceSearchPlaceholder: 'ค้นหาจังหวัด...',
    setupSubtext: 'เลือกเฉพาะที่เกี่ยวกับคุณจริง ๆ เพื่อให้คำแนะนำที่แม่นขึ้น',
    nurseSetupLabel: 'รูปแบบงานที่คุณสนใจ',
    hospitalSetupLabel: 'ความเร่งด่วนในการหาคน',
    userSetupLabel: 'ประเภทการดูแลที่ต้องการ',
    summaryTypes: '{count} ประเภทวิชาชีพ',
    summaryOptions: '{count} ตัวเลือกที่สนใจ',
    skipAll: 'ข้ามทั้งหมด',
    goBack: 'ย้อนกลับ',
    skipStep: 'ข้ามขั้นตอนนี้',
    next: 'ถัดไป',
    enterApp: 'เข้าแอปเลย',
  },"""


def inject(filepath, block, marker):
    """Insert block before the closing marker in the file."""
    content = filepath.read_text(encoding='utf-8')
    # Find the last occurrence of the marker
    idx = content.rfind(marker)
    if idx == -1:
        raise ValueError(f"Marker '{marker}' not found in {filepath}")
    # Insert the block before the marker
    new_content = content[:idx] + block + "\n" + content[idx:]
    filepath.write_text(new_content, encoding='utf-8')
    print(f"✅ Injected into {filepath.name} ({len(block)} chars)")


# en.ts ends with `};` — inject before the final `};`
inject(BASE / "en.ts", EN_BLOCK, "\n};")

# th.ts ends with `} as const;` — inject before the final `} as const;`
inject(BASE / "th.ts", TH_BLOCK, "\n} as const;")

print("Done! Dictionary entries added.")
